paths:
  /users:
    get:
      summary: Get a list of all users
      tags: [ Users ]
      responses:
        200:
          description: List of all users
    post:
      summary: Add a new driver
      tags: [ Users ]
      responses:
        201:
          description: The driver was successfully created
        400:
          description: Validation error
  /testing:
    get:
      summary: Get a list of all users
      tags: [ Users ]
      responses:
        200:
          description: List of all users
    post:
      summary: Add a new driver
      tags: [ Users ]
      responses:
        201:
          description: The driver was successfully created
        400:
          description: Validation error