paths:
  /comments/{id}:
    get:
      summary: Get comment by id
      tags: [ Comments ]
      parameters:
        - name: id
          in: path
          required: true
          description: Comment id
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: Comment found
        404:
          description: Comment not found

    put:
      summary: Update comment content
      tags: [ Comments ]
      parameters:
        - name: id
          in: path
          required: true
          description: Comment id
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  minLength: 20
                  maxLength: 300
      responses:
        204:
          description: Comment updated
        400:
          description: Validation error
        401:
          description: Unauthorized
        404:
          description: Comment not found

    delete:
      summary: Delete comment by id
      tags: [ Comments ]
      parameters:
        - name: id
          in: path
          required: true
          description: Comment id
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        204:
          description: Comment deleted
        401:
          description: Unauthorized
        404:
          description: Comment not found

  /comments/{id}/like-status:
    put:
      summary: Update like status for comment
      tags: [ Comments ]
      parameters:
        - name: id
          in: path
          required: true
          description: Comment id
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - likeStatus
              properties:
                likeStatus:
                  type: string
                  enum: [ Like, Dislike, None ]
      responses:
        204:
          description: Like status updated
        400:
          description: Validation error
        401:
          description: Unauthorized
        404:
          description: Comment not found