paths:
  /auth:
    get:
      summary: Get a list of all users
      tags: [ Auth ]
      responses:
        200:
          description: List of all users
    post:
      summary: Add a new user
      tags: [ Auth ]
      responses:
        201:
          description: The user was successfully created
        400:
          description: Validation error
